### ISSUE TITLE
nom start 无法运行，提示少文件

### ISSUE THREAD

**Issue by imsong52** [heiyu4585/graphql-express-mysql#1]
> node ./bin/www

module.js:540
    throw err;
    ^

Error: Cannot find module './routes/index'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/zhou/Projects/studyJS/graphql-express-mysql/app.js:8:13)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)[](url)

**Comment by myncepu** [comment]
应该是没有上传./routes目录
方便的话请 @heiyu4585 上传一下吧
🙏🙏

**Comment by heiyu4585** [comment]
@imsong52 @myncepu 已经上传,大意了,我试下了可以了,有问题在留言
