### ISSUE TITLE
Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by kmyw** [heiyu4585/graphql-express-mysql#3]
TypeError: Cannot read property 'query' of undefined
    at /home/graphql-express-mysql/util/util.js:8:24
    at Handshake.onConnect (/home/graphql-express-mysql/node_modules/mysql/lib/Pool.js:58:9)
    at Handshake.<anonymous> (/home/graphql-express-mysql/node_modules/mysql/lib/Connection.js:525:10)
    at Handshake._callback (/home/graphql-express-mysql/node_modules/mysql/lib/Connection.js:491:16)
    at Handshake.Sequence.end (/home/graphql-express-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Handshake.ErrorPacket (/home/graphql-express-mysql/node_modules/mysql/lib/protocol/sequences/Handshake.js:125:8)
    at Protocol._parsePacket (/home/graphql-express-mysql/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/graphql-express-mysql/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/graphql-express-mysql/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/graphql-express-mysql/node_modules/mysql/lib/protocol/Protocol.js:38:16)

**Comment by heiyu4585** [comment]
可以说下复现步骤吗

**Comment by kmyw** [comment]
就是按照你的代码来的，然后配置文件都改了，就是连不上，我用的docker部署的

**Comment by heiyu4585** [comment]
我本地可以,你是不是 mysql包没有正确安装.

**Comment by kmyw** [comment]
大牛，你微信多少，方便的话，可以加微信聊，这是我的 wxd_56987
